### ISSUE TITLE
Cannot grab the data after the 50th spot on FantasyPros

### ISSUE THREAD

**Issue by AlexMarey** [AlexMarey/FantasyTracker#1]
Ran into a problem with grabbing the 51st row in the player table.

Data leading up to the error: 

['48', 'Kyle JuszczykK. Juszczyk SF', 'vs.  OAK', '45', '56', '50.2', '2.2']
Kyle JuszczykK. Juszczyk SF
['49', 'Theo RiddickT. Riddick DET', 'at  MIN', '38', '61', '50.6', '3.9']
Theo RiddickT. Riddick DET
['50', 'Royce FreemanR. Freeman DEN', 'vs.  HOU', '32', '64', '48.7', '6.9']
Royce FreemanR. Freeman DEN
["50\n\r\n                                              googletag.cmd.push(function() { googletag.display('div-gpt-ad-1404326895972-0'); });"]
Traceback (most recent call last):
  File "main.py", line 135, in <module>
    player_rankings_std[p] = get_players_rankings(url_rankings_std, league_size, p)
  File "main.py", line 92, in get_players_rankings
    player_name = parse_names(row[1])
IndexError: list index out of range

**Comment by AlexMarey** [comment]
Code now checks the length of the data before adding it to the dictionary.
